# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comentarios.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63omentarios.proto\x12\x0b\x43omentarios\".\n\nComentario\x12\r\n\x05\x61utor\x18\x01 \x01(\t\x12\x11\n\tcontenido\x18\x02 \x01(\t\"\'\n\x13\x43onsultaComentarios\x12\x10\n\x08\x63\x61ntidad\x18\x01 \x01(\x05\"+\n\tRespuesta\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\"@\n\x10ListaComentarios\x12,\n\x0b\x63omentarios\x18\x01 \x03(\x0b\x32\x17.Comentarios.Comentario2\xb2\x01\n\x12\x43omentariosService\x12\x45\n\x12PublicarComentario\x12\x17.Comentarios.Comentario\x1a\x16.Comentarios.Respuesta\x12U\n\x12ObtenerComentarios\x12 .Comentarios.ConsultaComentarios\x1a\x1d.Comentarios.ListaComentariosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comentarios_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMENTARIO']._serialized_start=34
  _globals['_COMENTARIO']._serialized_end=80
  _globals['_CONSULTACOMENTARIOS']._serialized_start=82
  _globals['_CONSULTACOMENTARIOS']._serialized_end=121
  _globals['_RESPUESTA']._serialized_start=123
  _globals['_RESPUESTA']._serialized_end=166
  _globals['_LISTACOMENTARIOS']._serialized_start=168
  _globals['_LISTACOMENTARIOS']._serialized_end=232
  _globals['_COMENTARIOSSERVICE']._serialized_start=235
  _globals['_COMENTARIOSSERVICE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
